-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1059
--   at:        2017-08-14 23:17:46 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE city (
    id     INTEGER
        CONSTRAINT nnc_city_city_id NOT NULL IDENTITY(1,1),
    name   NVARCHAR(50)
        CONSTRAINT nnc_city_name NOT NULL
);

CREATE TABLE day_type (
    id     INTEGER NOT NULL IDENTITY(1,1),
    name   NVARCHAR(50) NOT NULL
);

CREATE TABLE departure (
    id               INTEGER NOT NULL IDENTITY(1,1),
    departure_time   DATE NOT NULL,
    day_type_id      INTEGER NOT NULL
);

CREATE TABLE line (
    id             INTEGER NOT NULL IDENTITY(1,1),
    "number"       INTEGER NOT NULL,
    line_type_id   INTEGER NOT NULL
);

CREATE TABLE line_departure (
    line_id        INTEGER NOT NULL,
    departure_id   INTEGER NOT NULL
);


CREATE TABLE line_route (
    line_id                      INTEGER NOT NULL,
    two_stations_connection_id   INTEGER NOT NULL
);

CREATE TABLE line_type (
    id     INTEGER NOT NULL IDENTITY(1,1),
    name   NVARCHAR(50) NOT NULL
);

CREATE TABLE station (
    id                INTEGER NOT NULL IDENTITY(1,1),
    slot_id           INTEGER NOT NULL,
    city_id           INTEGER NOT NULL,
    station_name_id   INTEGER NOT NULL
);

CREATE TABLE station_name (
    id     INTEGER NOT NULL IDENTITY(1,1),
    name   NVARCHAR(50) NOT NULL
);

CREATE TABLE two_stations_connection (
    id                  INTEGER NOT NULL IDENTITY(1,1),
    station_id_first    INTEGER NOT NULL,
    station_id_second   INTEGER NOT NULL,
    travel_distance     INTEGER NOT NULL,
    travel_time         INTEGER NOT NULL
);


ALTER TABLE day_type ADD CONSTRAINT day_type_fkey PRIMARY KEY ( id );

ALTER TABLE line_departure ADD CONSTRAINT line_departure_pkey PRIMARY KEY ( line_id,departure_id );

ALTER TABLE line_type ADD CONSTRAINT line_type_pkey PRIMARY KEY ( id );

ALTER TABLE city ADD CONSTRAINT city_pkey PRIMARY KEY ( id );

ALTER TABLE station ADD CONSTRAINT station_pkey PRIMARY KEY ( id );

ALTER TABLE line_route ADD CONSTRAINT line_route_pkey PRIMARY KEY ( line_id,two_stations_connection_id );

ALTER TABLE station_name ADD CONSTRAINT station_name_pkey PRIMARY KEY ( id );

ALTER TABLE line ADD CONSTRAINT line_pkey PRIMARY KEY ( id );

ALTER TABLE departure ADD CONSTRAINT departure_pkey PRIMARY KEY ( id );

ALTER TABLE two_stations_connection ADD CONSTRAINT two_stations_connection_pkey PRIMARY KEY ( id );

ALTER TABLE station
    ADD CONSTRAINT city_id_fkey FOREIGN KEY ( city_id )
        REFERENCES city ( id );

ALTER TABLE departure
    ADD CONSTRAINT day_type_id_fkey FOREIGN KEY ( day_type_id )
        REFERENCES day_type ( id );

ALTER TABLE line_departure
    ADD CONSTRAINT departure_id_fkey FOREIGN KEY ( departure_id )
        REFERENCES departure ( id )
            ON DELETE CASCADE;

ALTER TABLE line_route
    ADD CONSTRAINT line_id_fkey1 FOREIGN KEY ( line_id )
        REFERENCES line ( id )
            ON DELETE CASCADE;

ALTER TABLE line_departure
    ADD CONSTRAINT line_id_fkey2 FOREIGN KEY ( line_id )
        REFERENCES line ( id )
            ON DELETE CASCADE;

ALTER TABLE line
    ADD CONSTRAINT line_type_id_fkey FOREIGN KEY ( line_type_id )
        REFERENCES line_type ( id );

ALTER TABLE two_stations_connection
    ADD CONSTRAINT station_id_fkey1 FOREIGN KEY ( station_id_first )
        REFERENCES station ( id );

ALTER TABLE two_stations_connection
    ADD CONSTRAINT station_id_fkey2 FOREIGN KEY ( station_id_second )
        REFERENCES station ( id );

ALTER TABLE station
    ADD CONSTRAINT station_name_id_fkey FOREIGN KEY ( station_name_id )
        REFERENCES station_name ( id );

ALTER TABLE line_route
    ADD CONSTRAINT two_stations_id_fkey FOREIGN KEY ( two_stations_connection_id )
        REFERENCES two_stations_connection ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
